### ISSUE TITLE
Readme not lit enough

### ISSUE THREAD

**Issue by LoggeL** [qqwer1/GoS-Lua#2]
Hello sir, I've seen your readme.txt but I'm not sure that you could describe that as lit. I would suggest that you improve the lit-ness in the next update or pepe would be very sad. 
Kind regards 
Laggo

**Comment by LoggeL** [comment]
🔥🔥🔥🔥🔥🔥🔥

**Comment by Xh4H** [comment]
#1

**Comment by tefazalat** [comment]
sry but i don't remember what readme.txt that i sent to you sir could u explain ?


On Thu, Dec 7, 2017 at 5:15 PM, Juan <notifications@github.com<mailto:notifications@github.com>> wrote:

#1<https://github.com/qqwer1/GoS-Lua/pull/1>
